name: "Integrate"

on:
  pull_request: ~
  push:
    branches:
      - "*"
      - master

jobs:
  psalm-test:
    name: "Psalm test"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Determine composer cache directory"
        id: determine-composer-cache-directory
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: "Install highest dependencies from composer.json"
        run: composer install --no-interaction --no-progress --no-suggest

      - name: "Show used stubs"
        run:  tail -n +1 stubs/*

      - name: "Run vimeo/psalm"
        run: |
          echo "Running psalm on the following code" \
          && echo "\n------------------ TEST CODE -----------------\n" \
          && cat test.php \
          && echo "\n---------------- END TEST CODE ---------------\n" \
          && echo "Using `vendor/bin/psalm --version`" \
          && echo "---------------- STARTING TEST ---------------\n" \
          && vendor/bin/psalm --no-cache --show-info=true --stats
